### ISSUE TITLE
Empty input

### ISSUE THREAD

**Issue by semihsmg** [BernardoPiedade/The-Hacker-Game-Ruining-The-World#2]
Empty inputs are giving exception error. When the game gives options, hit enter without typing "1" or "2" program terminates itself.

**Comment by BernardoPiedade** [comment]
Hi semihsmg,

I've notice that error in the code, and I'm trying to fix it, in the next update of the game, that is coming soon, that error wont be bummer anymore.

Thank you,
Bernardo Piedade

**Comment by RetiredQQ** [comment]
` var r = Console.ReadLine();
            if (string.IsNullOrEmpty(r))
            {
                MiniMenu();
            }
            int opGame = int.Parse(r);`
